const IMAGES = {
    LOAD: 'IMAGES_LOAD',
    LOAD_SUCCESS: 'IMAGES_LOAD_SUCCESS',
    LOAD_FAIL: 'IMAGES_LOAD_FAIL',
};
const IMAGE = {
    LOAD: 'IMAGE_LOAD',
    LOAD_SUCCESS: 'IMAGE_LOAD_SUCCESS',
    LOAD_FAIL: 'IMAGE_LOAD_FAIL',
};


export {IMAGES,IMAGE};
